# Generated by Django 3.2.25 on 2024-08-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
