global:
  resolve_timeout: 5m

route:
  receiver: "gmail-notifications"
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: "gmail-notifications"
    email_configs:
      - to: "SMTP_TO"
        from: "SMTP_FROM"
        smarthost: "SMTP_SMARTHOST"
        auth_username: "SMTP_AUTH_USERNAME"
        auth_identity: "SMTP_AUTH_IDENTITY"
        auth_password: "SMTP_AUTH_PASSWORD"
        send_resolved: true
