# # http://host.docker.internal:9090

# global:
#   scrape_interval: 15s
#   scrape_timeout: 10s
# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090']
#   - job_name: 'my-app'
#     static_configs:
#       - targets: ['my-app:8080']a

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets: 
        - django:8000
