
services:
  web:
    build: ./django
    command: gunicorn trans.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django:/code
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  postgres_data:
