{
 "title": "Application Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Responses",
   "type": "table",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "django_http_responses_total_by_status_total"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "histogram",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "django_http_requests_latency_including_middlewares_seconds"
    }
   ]
  },
  {
   "title": "Database Query Duration",
   "type": "histogram",
   "gridPos": { "x": 0, "y": 5, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "django_db_query_duration_seconds"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "x": 6, "y": 5, "w": 6, "h": 5 },
   "targets": [
    { "expr": "process_virtual_memory_bytes" }
   ]
  },
  {
   "title": "Process Information",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 10, "w": 6, "h": 5 },
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  }
 ]
}